### ISSUE TITLE
[BUG] [Archlinux] track upstream bug and workaround

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/airflow-formula#3]
### Versions reports (master & minion)

```
Salt Version:
          Salt: 3002.2

Dependency Versions:
          cffi: 1.14.4
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.2
       libgit2: Not Installed
      M2Crypto: 0.36.0
          Mako: 1.1.3
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.0 (default, Oct  7 2020, 23:09:01)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 19.0.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.3

System Versions:
          dist: arch rolling n/a
        locale: utf-8
       machine: x86_64
       release: 5.9.11-arch2-1
        system: Linux
       version: Arch Linux rolling n/a
```

### Pillar / config used

```
postgres:
  users:
    airflow:
      ensure: present
      password: airflow
      createdb: true
      inherit: true
      createroles: true
      replication: true
  databases:
    airflow:
      owner: airflow
  acls:
    - ['local', 'airflow', 'airflow', 'md5']
    - ['local', 'all', 'all', 'peer']
    - ['host', 'all', 'all', '127.0.0.1/32', 'md5']
    - ['host', 'all', 'all', '::1/128', 'md5']
    - ['local', 'replication', 'all', 'peer']
    - ['host', 'replication', 'all', '127.0.0.1/32', 'md5']
    - ['host', 'replication', 'all', '::1/128', 'md5']

airflow:
  config:
    airflow:
      content:
        executor: LocalExecutor
  service:
    airflow:
      enabled:
        - airflow-flower
        - airflow-scheduler
        - airflow-webserver
        - airflow-worker
  pkg:
    airflow:
      version: 1.10.13
      use_upstream: pip
      extras:
        - postgres
        - google
  dir:
    airflow:
      config: /home/airflow/airflow
  linux:
    altpriority: 0   # zero disables alternatives

  # Just for testing purposes
  winner: pillar
  added_in_pillar: pillar_value

```

---

### Describe the bug

```
          ID: airflow-service-install-database
    Function: cmd.run
        Name: /home/airflow/airflow/bin/airflow initdb
      Result: False
     Comment: Command "/home/airflow/airflow/bin/airflow initdb" run
     Started: 16:55:40.274152
    Duration: 979.898 ms
     Changes:
              ----------
              pid:
                  6757
              retcode:
                  1
              stderr:
                  Traceback (most recent call last):
                    File "/home/airflow/airflow/bin/airflow", line 26, in <module>
                      from airflow.bin.cli import CLIFactory
                    File "/home/airflow/airflow/lib/python3.9/site-packages/airflow/bin/cli.py", line 94, in <module>
                      api_module = import_module(conf.get('cli', 'api_client'))  # type: Any
                    File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
                      return _bootstrap._gcd_import(name[level:], package, level)
                    File "/home/airflow/airflow/lib/python3.9/site-packages/airflow/api/client/local_client.py", line 24, in <module>
                      from airflow.api.common.experimental import delete_dag
                    File "/home/airflow/airflow/lib/python3.9/site-packages/airflow/api/common/experimental/delete_dag.py", line 26, in <module>
                      from airflow.models.serialized_dag import SerializedDagModel
                    File "/home/airflow/airflow/lib/python3.9/site-packages/airflow/models/serialized_dag.py", line 35, in <module>
                      from airflow.serialization.serialized_objects import SerializedDAG
                    File "/home/airflow/airflow/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py", line 28, in <module>
                      import cattr
                    File "/home/airflow/airflow/lib/python3.9/site-packages/cattr/__init__.py", line 1, in <module>
                      from .converters import Converter, GenConverter, UnstructureStrategy
                    File "/home/airflow/airflow/lib/python3.9/site-packages/cattr/converters.py", line 17, in <module>
                      from attr import fields, resolve_types
                  ImportError: cannot import name 'resolve_types' from 'attr' (/home/airflow/airflow/lib/python3.9/site-packages/attr/__init__.py)
              stdout:
```

### Steps to reproduce the bug

- Use Salt Py3: https://github.com/saltstack-formulas/salter/issues/81#issue-756270586
- clone this repo
- cp ./airflow-formula/pillar-example /srv/pillar/
- Run highstate with `redis, postgres, airflow`
And finally this: https://github.com/apache/airflow/issues/11965

**Comment by noelmcloughlin** [comment]
Archlinux has python 3.9.    Workarounds to try:
```
pip install apache-airflow==1.10.12 \
 --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-1.10.12/constraints-3.8.txt"
``` 
or
`cattr==1.0.0`

**Comment by noelmcloughlin** [comment]
Solution: `cattr==1.0.0`
